signing_table = [
"*@DOMAIN DOMAIN",
"*@*.DOMAIN DOMAIN",
];

key_table = [
"DOMAIN DOMAIN:default:/var/lib/rspamd/dkim/DOMAIN.default.key",
];

use_domain = "envelope";
allow_hdrfrom_mismatch = true;
allow_hdrfrom_mismatch_sign_networks = true;
allow_username_mismatch = true;
use_esld = true;
sign_authenticated = false;
