use = ["authentication-results", "remove-headers", "spam-header", "add_dmarc_allow_header"];

routines {
  remove-headers {
    headers {
      "X-Spam" = 0;
      "X-Spamd-Bar" = 0;
      "X-Spam-Level" = 0;
      "X-Spam-Status" = 0;
      "X-Spam-Flag" = 0;
    }
  }
  authentication-results {
    header = "X-Authentication-Results";
    remove = 0;
  }
  spam-header {
    header = "X-Spam";
    value = "Yes";
    remove = 0;
  }
}

custom {
  add_dmarc_allow_header = <<EOD
return function(task, common_meta)
  if task:has_symbol('DMARC_POLICY_ALLOW') then
    return nil,
    {['X-Dmarc-Allow'] = 'Yes'},
    {['X-Dmarc-Allow'] = 0},
    {}
  end

  return nil,
  {},
  {['X-Dmarc-Allow'] = 0},
  {}
end
EOD;
}
